---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - applicationName: app-example
  template:
    metadata:
      name: dev-{{applicationName}}
    spec:
      project: default
      destination:
        namespace: dev
        server: https://kubernetes.default.svc
      source:
        repoURL: git@github.com:Ghunter43/public-test.git
        targetRevision: main
        path: apps/{{applicationName}}/overlays/dev
      syncPolicy: 
        automated:
          prune: false
