apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  template:
    spec:
      containers:
        - name: nginx
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "1m"
              memory: "1Mi"